name: Free VPS

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ngrok & Setup SSH
        run: |
          # Install OpenSSH server
          sudo apt update && sudo apt install -y openssh-server
          
          # Set root password and enable root login
          echo "root:password" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Start Ngrok Tunnel
        run: |
          # Install Ngrok
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

          # Set Ngrok authentication token from GitHub Secrets
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
          # Start the Ngrok tunnel and get the public URL
          ngrok tcp 22 > /dev/null &
          sleep 5
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url

      - name: Keep VPS Running
        run: sleep 6h  # Runs for 6 hours to simulate a "VPS session"
